shac/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root "home#index"

  devise_for :crashers
  resources :crashers, :only => [:create, :new, :show, :edit]

  devise_for :hosts
  resources :hosts, :only => [:create, :new, :show, :edit]

  resources :crashings, except: [:edit, :update, :show] do
    resources :reviews, only: [:new, :create]
  end

end

shac/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right nav-header">
<% if host_signed_in? %>
  Logged in as <strong><%= current_host.email %></strong>.
  <%= link_to 'Edit profile', edit_host_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_host_session_path, method: :delete, :class => 'navbar-link'  %>
<% elsif crasher_signed_in? %>
	Logged in as <strong><%= current_crasher.email %></strong>.
  <%= link_to 'Edit profile', edit_crasher_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_crasher_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up as host", new_host_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login as host", new_host_session_path, :class => 'navbar-link'  %> |
  <%= link_to "Sign up as crasher", new_crasher_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login as crasher", new_crasher_session_path, :class => 'navbar-link'  %>
<% end %>


<%= yield %>

</body>
</html>